packages:
  - packages/*
  - apps/*

onlyBuiltDependencies:
  - '@prisma/client'
  - '@prisma/engines'
  - '@sentry/cli'
  - esbuild
  - electron
  - electron-winstaller
  - prisma
  - sharp
  - unrs-resolver
