import { randomBytes, scryptSync } from "node:crypto";
import OAuth2Server from "@node-oauth/oauth2-server";
import { assert } from "@hackclub/lapse-shared";
import z from "zod";
import jwt from "jsonwebtoken";

import * as db from "@/generated/prisma/client.js";

import { database, redis } from "@/db.js";
import { env } from "@/env.js";
import { logWarning } from "@/logging.js";
import type { FastifyRequest } from "fastify";
import { getAllOAuthScopes, type LapseOAuthScope } from "@hackclub/lapse-api";

function hashServiceSecret(secret: string): string {
    const salt = randomBytes(16).toString("hex");
    const hashed = scryptSync(secret, salt, 64).toString("hex");
    return `${salt}:${hashed}`;
}

function decodeAccessToken(accessToken: string): AccessTokenJwt | Error {
    try {
        return AccessTokenJwtSchema.parse(
            jwt.verify(accessToken, env.JWT_SECRET_ACCESS_TOKENS)
        );
    }
    catch (err) {
        logWarning("Access token is either expired, forged, or has an incorrect schema.", { err });
        return err as Error;
    }
}

/**
 * Defines the fields of an authorization code stored on Redis.
 */
type AuthorizationCodePayload = z.infer<typeof AuthorizationCodePayloadSchema>;
const AuthorizationCodePayloadSchema = z.object({
    /**
     * The user ID the authorization code was issued for.
     */
    sub: z.string(),

    /**
     * The client ID the authorization code was issued for.
     */
    cid: z.string(),

    /**
     * The scopes to grant to the authentication token that will result from this authorization code.
     */
    scp: z.array(z.string()).optional(),

    /**
     * The redirect URI for the code.
     */
    uri: z.string(),

    /**
     * Code challenge value.
     */
    ccv: z.string().optional(),

    /**
     * Code challenge method.
     */
    ccm: z.string().optional(),

    /**
     * The expiration date of the authorization code, specified in milliseconds from the Unix epoch.
     */
    exp: z.number()
});

/**
 * Defines the fields of an access token stored as a JWT.
 */
type AccessTokenPayload = z.infer<typeof AccessTokenPayloadSchema>;
const AccessTokenPayloadSchema = z.object({
    /**
     * The ID of the user the access token was issued for.
     */
    sub: z.string(),

    /**
     * The scopes the caller is entitled to.
     */
    scp: z.array(z.string()),

    /**
     * The client ID this access token was generated for.
     */
    cid: z.string()
});

/**
 * Extends `AccessTokenPayload` with fields automatically generated by `jsonwebtoken`.
 */
type AccessTokenJwt = z.infer<typeof AccessTokenJwtSchema>;
const AccessTokenJwtSchema = AccessTokenPayloadSchema.extend({
    /**
     * The expiration date of the authorization code, specified in seconds from the Unix epoch. 
     */
    exp: z.number()
})

// reference: https://github.com/14gasher/oauth-example/blob/master/auth/oauth/model.js

class LapseAuthorizationCodeModel implements OAuth2Server.AuthorizationCodeModel {
    private async clientById(clientId: string) {
        const client = await database().serviceClient.findFirst({
            where: { clientId },
            include: { grants: true }
        });

        return client && !client.revokedAt ? this.dtoDbClient(client) : null;
    }

    private dtoDbClient(client: db.ServiceClient): OAuth2Server.Client {
        return {
            id: client.clientId,
            redirectUris: client.redirectUris,
            grants: ["authorization_code", "refresh_token"]
        };
    }

    async getClient(clientId: string, clientSecret: string): Promise<OAuth2Server.Client | OAuth2Server.Falsey> {
        const client = await database().serviceClient.findFirst({
            include: { grants: true },
            where: {
                clientId,

                // Docs state "Can be null." for `clientSecret`, but our typings don't have that... just to be safe, we check if it's falsy.
                clientSecretHash: clientSecret ? hashServiceSecret(clientSecret) : undefined
            }
        });

        if (!client) {
            logWarning(`Attempted to find a non-existent client ${clientId} (or secret is wrong).`);
            return null;
        }

        return this.dtoDbClient(client);
    }

    async saveAuthorizationCode(
        code: Pick<OAuth2Server.AuthorizationCode, "authorizationCode" | "expiresAt" | "redirectUri" | "scope" | "codeChallenge" | "codeChallengeMethod">,
        client: OAuth2Server.Client,
        user: OAuth2Server.User
    ): Promise<OAuth2Server.AuthorizationCode | OAuth2Server.Falsey> {
        await redis().set(
            `lapse:auth:authcode:${code.authorizationCode}`,
            JSON.stringify(
                {
                    cid: client.id,
                    sub: user["id"],
                    scp: code.scope,
                    uri: code.redirectUri,
                    ccv: code.codeChallenge,
                    ccm: code.codeChallengeMethod,
                    exp: code.expiresAt.getTime()
                } satisfies AuthorizationCodePayload
            ),
            "PXAT", code.expiresAt.getTime() // PXAT = expires at, milliseconds, unix time
        );

        return {
            client,
            user,
            authorizationCode: code.authorizationCode,
            expiresAt: code.expiresAt,
            redirectUri: code.redirectUri,
            codeChallenge: code.codeChallenge,
            codeChallengeMethod: code.codeChallengeMethod,
            scope: code.scope
        };
    }

    async getAuthorizationCode(authorizationCode: string): Promise<OAuth2Server.AuthorizationCode | OAuth2Server.Falsey> {
        const raw = await redis().get(`lapse:auth:authcode:${authorizationCode}`);
        if (!raw) {
            logWarning(`Could not get OAuth authorization code - ${authorizationCode} is either expired or doesn't exist.`);
            return null;
        }

        let payload: AuthorizationCodePayload;

        try {
            payload = AuthorizationCodePayloadSchema.parse(JSON.parse(raw));
        }
        catch (err) {
            logWarning(`OAuth authorization code ${authorizationCode} stored in Redis is malformed!`, { err });
            return null;
        }

        const client = await this.clientById(payload.cid);
        if (!client) {
            logWarning(`The client ${payload.cid} that issued authorization code ${authorizationCode} either doesn't exist or has been revoked.`, { payload });
            return null;
        }

        return {
            authorizationCode,
            client,
            expiresAt: new Date(payload.exp),
            redirectUri: payload.uri,
            codeChallenge: payload.ccv,
            codeChallengeMethod: payload.ccm,
            scope: payload.scp,
            user: {
                id: payload.sub
            }
        };
    }

    async revokeAuthorizationCode(code: OAuth2Server.AuthorizationCode): Promise<boolean> {
        return (await redis().del(`lapse:auth:authcode:${code.authorizationCode}`)) == 1;
    }

    // We take control of access token generation, as those are JWTs in our case. This allows us to skip hitting the database every single time we want to check user authorization - but, as we store the
    // issued-at date for each JWT, we can store a `tokensValidFrom` on our `User` model (which we fetch anyways for each authenticated request) for immidiate revocation of all tokens in case a
    // user gets compromised.
    async generateAccessToken(client: OAuth2Server.Client, user: OAuth2Server.User, scope: string[]): Promise<string> {
        assert("id" in user && typeof user["id"] === "string", "'user' object provided to generateAccessToken was invalid");

        return jwt.sign(
            {
                sub: user["id"],
                cid: client.id,
                scp: scope
            } satisfies AccessTokenPayload,
            env.JWT_SECRET_ACCESS_TOKENS,
            { expiresIn: "30d" } // TODO: We currently don't do refresh tokens. We should probably do that.
        );
    }

    async saveToken(token: OAuth2Server.Token, client: OAuth2Server.Client, user: OAuth2Server.User): Promise<OAuth2Server.Token | OAuth2Server.Falsey> {
        // Our tokens are JWTs, so there's no need to save them. We still do a sanity check on them - just in case!
        return this.getAccessToken(token.accessToken);
    }

    async getAccessToken(accessToken: string): Promise<OAuth2Server.Token | OAuth2Server.Falsey> {
        let token: AccessTokenJwt | string;

        try {
            token = AccessTokenJwtSchema.parse(
                jwt.verify(accessToken, env.JWT_SECRET_ACCESS_TOKENS)
            );
        }
        catch (err) {
            logWarning("Access token is either expired, forged, or has an incorrect schema.", { err });
            return null;
        }

        const client = await this.clientById(token.cid);
        if (!client) {
            logWarning(`The client ${token.cid} that issued access token for user ${token.sub} either doesn't exist or has been revoked.`, { token });
            return null;
        }

        return {
            accessToken,
            accessTokenExpiresAt: new Date(token.exp * 1000),
            client,
            scope: token.scp,
            user: {
                id: token.sub
            }
        };
    }
}

export const oauthSrv = new OAuth2Server({
    model: new LapseAuthorizationCodeModel(),
    accessTokenLifetime: 60 * 60 * 24 * 30, // 30d
});

export async function getAuthenticatedUser(req: FastifyRequest): Promise<{ user: db.User | null, scopes: LapseOAuthScope[] }> {
    if (!req.headers.authorization || !req.headers.authorization.startsWith("Bearer "))
        return { user: null, scopes: [] };

    const token = decodeAccessToken(req.headers.authorization.substring("Bearer ".length));
    if (token instanceof Error) {
        logWarning("Could not decode access token!", { error: token });
        return { user: null, scopes: [] };
    }

    try {
        const user = await database().user.findFirst({
            where: { id: token.sub }
        });

        const allScopes = new Set(getAllOAuthScopes());
        if (!token.scp.every(x => allScopes.has(x as LapseOAuthScope))) {
            logWarning(`Unknown scopes present in access token; denying auth! All scopes: ${token.scp.join(", ")}`);
            return { user: null, scopes: [] };
        }

        return {
            user,
            scopes: token.scp as LapseOAuthScope[]
        };
    }
    catch (error) {
        logWarning(`Could not fetch user ${token.sub} (authenticated via client ${token.cid})!`, { error });
        return { user: null, scopes: [] };
    }
}
